CREATE DATABASE db_zicare;
USE db_zicare;

CREATE TABLE user(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL,
password VARCHAR(500) NOT NULL,
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL
);